let students=[], staff=[], classes=[], announcements=[], gallery=[], site={};
async function api(url,opt={}){const r=await fetch(url,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Request failed');return d}
async function boot(){try{const m=await api('/api/me');if(m.admin){showDash();await Promise.all([loadStudents(),loadStaff(),loadClasses(),loadAnnouncements(),loadGallery(),loadSite()]);}else document.getElementById('login').classList.remove('hidden')}catch(e){document.getElementById('login').classList.remove('hidden')}}
async function login(){try{await api('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:document.getElementById('password').value})});showDash();await Promise.all([loadStudents(),loadStaff(),loadClasses(),loadAnnouncements(),loadGallery(),loadSite()]);}catch(e){alert(e.message)}}
function showDash(){document.getElementById('login').classList.add('hidden');document.getElementById('dashboard').classList.remove('hidden')}
async function logout(){await api('/api/logout',{method:'POST'});location.reload()}
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function closeModal(id){document.getElementById(id).classList.add('hidden')}
function openModal(id){document.getElementById(id).classList.remove('hidden')}
async function loadStudents(){try{const q=document.getElementById('search')?.value||'', cls=document.getElementById('studentClassFilter')?.value||'';students=await api('/api/students?q='+encodeURIComponent(q)+'&class_name='+encodeURIComponent(cls));renderStudents();const s=await api('/api/stats');document.getElementById('total').textContent=s.total;document.getElementById('active').textContent=s.active;document.getElementById('classCount').textContent=s.classes.length;document.getElementById('staffCount').textContent=s.staff;populateClassFilters(s.classes)}catch(e){alert(e.message)}}
function populateClassFilters(stats){const a=document.getElementById('studentClassFilter'),b=document.getElementById('smsClass');if(!a||!b)return;const current=a.value, current2=b.value;const names=[...new Set(stats.map(x=>x.class_name).filter(Boolean))];a.innerHTML='<option value="">All classes</option>'+names.map(x=>`<option>${esc(x)}</option>`).join('');b.innerHTML='<option value="">All active parents</option>'+names.map(x=>`<option>${esc(x)}</option>`).join('');a.value=current;b.value=current2}
function renderStudents(){const tb=document.getElementById('students');if(!tb)return;tb.innerHTML=students.map(s=>`<tr><td><input class="student-check" type="checkbox" value="${s.id}"></td><td><img class="avatar" src="${s.photo||'/assets/Logo Al Azan/Logo Al Azan-1.png'}"></td><td>${esc(s.admission_no)}</td><td><b>${esc(s.name)}</b></td><td>${esc(s.father_name)}</td><td>${esc(s.class_name)} ${esc(s.section)}</td><td>${esc(s.phone)}</td><td><span class="status ${s.status==='Active'?'ok':'off'}">${esc(s.status)}</span></td><td><button class="small-btn" onclick="openStudent(${s.id})">Edit</button> <button class="small-btn danger" onclick="removeStudent(${s.id})">Delete</button></td></tr>`).join('')||'<tr><td colspan="9">No students found.</td></tr>'}
function toggleAll(el){document.querySelectorAll('.student-check').forEach(x=>x.checked=el.checked)}
function openStudent(id){const s=students.find(x=>x.id===id);openModal('studentModal');document.getElementById('modalTitle').textContent=s?'Edit Student':'Add Student';['sid','admission_no','name','father_name','class_name','section','dob','bform','phone','address','status'].forEach(k=>{const el=document.getElementById(k);if(el)el.value=k==='sid'?(s?.id||''):(s?(s[k]||''):k==='status'?'Active':'')});document.getElementById('photo').value=''}
document.getElementById('studentForm').addEventListener('submit',async e=>{e.preventDefault();const id=document.getElementById('sid').value,fd=new FormData(e.target);try{await api(id?'/api/students/'+id:'/api/students',{method:id?'PUT':'POST',body:fd});closeModal('studentModal');await loadStudents()}catch(err){alert(err.message)}});
async function removeStudent(id){if(!confirm('Delete this student record?'))return;try{await api('/api/students/'+id,{method:'DELETE'});await loadStudents()}catch(e){alert(e.message)}}

async function loadStaff(){staff=await api('/api/staff');document.getElementById('staffGrid').innerHTML=staff.map(s=>`<article class="manage-card"><img src="${s.photo||'/assets/Logo Al Azan/Logo Al Azan-1.png'}"><div><h3>${esc(s.name)}</h3><b>${esc(s.role)}</b><p>${esc(s.bio)}</p><button class="small-btn" onclick="openStaff(${s.id})">Edit</button> <button class="small-btn danger" onclick="deleteStaff(${s.id})">Delete</button></div></article>`).join('')||'<p>No staff added yet.</p>'}
function openStaff(id){const s=staff.find(x=>x.id===id);openModal('staffModal');document.getElementById('staffModalTitle').textContent=s?'Edit Staff':'Add Staff';document.getElementById('staffId').value=s?.id||'';document.getElementById('staffName').value=s?.name||'';document.getElementById('staffRole').value=s?.role||'';document.getElementById('staffBio').value=s?.bio||'';document.getElementById('staffSort').value=s?.sort_order||0;document.getElementById('staffPhoto').value=''}
document.getElementById('staffForm').addEventListener('submit',async e=>{e.preventDefault();const id=document.getElementById('staffId').value;try{await api(id?'/api/staff/'+id:'/api/staff',{method:id?'PUT':'POST',body:new FormData(e.target)});closeModal('staffModal');loadStaff()}catch(err){alert(err.message)}});
async function deleteStaff(id){if(confirm('Delete this staff profile?')){await api('/api/staff/'+id,{method:'DELETE'});loadStaff()}}

async function loadClasses(){classes=await api('/api/classes');document.getElementById('classes').innerHTML=classes.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.section)}</td><td>${esc(c.teacher)}</td><td>${esc(c.status)}</td><td><button class="small-btn" onclick="openClass(${c.id})">Edit</button> <button class="small-btn danger" onclick="deleteClass(${c.id})">Delete</button></td></tr>`).join('')||'<tr><td colspan="5">No classes added.</td></tr>'}
function openClass(id){const c=classes.find(x=>x.id===id);openModal('classModal');document.getElementById('classModalTitle').textContent=c?'Edit Class':'Add Class';document.getElementById('classId').value=c?.id||'';document.getElementById('className').value=c?.name||'';document.getElementById('classSection').value=c?.section||'';document.getElementById('classTeacher').value=c?.teacher||'';document.getElementById('classDescription').value=c?.description||'';document.getElementById('classStatus').value=c?.status||'Active'}
document.getElementById('classForm').addEventListener('submit',async e=>{e.preventDefault();const id=document.getElementById('classId').value;const body=Object.fromEntries(new FormData(e.target));try{await api(id?'/api/classes/'+id:'/api/classes',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});closeModal('classModal');loadClasses()}catch(err){alert(err.message)}});
async function deleteClass(id){if(confirm('Delete this class?')){await api('/api/classes/'+id,{method:'DELETE'});loadClasses()}}

async function loadAnnouncements(){announcements=await api('/api/announcements');document.getElementById('announcements').innerHTML=announcements.map(a=>`<article class="manage-card text-card"><div><span class="kicker">${esc(a.date)}</span><h3>${esc(a.title)}</h3><p>${esc(a.body)}</p><span class="status ${a.status==='Published'?'ok':'off'}">${esc(a.status)}</span><div class="card-actions"><button class="small-btn" onclick="openAnnouncement(${a.id})">Edit</button> <button class="small-btn danger" onclick="deleteAnnouncement(${a.id})">Delete</button></div></div></article>`).join('')||'<p>No announcements yet.</p>'}
function openAnnouncement(id){const a=announcements.find(x=>x.id===id);openModal('announcementModal');document.getElementById('announcementModalTitle').textContent=a?'Edit Announcement':'Add Announcement';document.getElementById('announcementId').value=a?.id||'';document.getElementById('announcementTitle').value=a?.title||'';document.getElementById('announcementDate').value=a?.date||new Date().toISOString().slice(0,10);document.getElementById('announcementBody').value=a?.body||'';document.getElementById('announcementStatus').value=a?.status||'Published'}
document.getElementById('announcementForm').addEventListener('submit',async e=>{e.preventDefault();const id=document.getElementById('announcementId').value,body=Object.fromEntries(new FormData(e.target));try{await api(id?'/api/announcements/'+id:'/api/announcements',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});closeModal('announcementModal');loadAnnouncements()}catch(err){alert(err.message)}});
async function deleteAnnouncement(id){if(confirm('Delete this announcement?')){await api('/api/announcements/'+id,{method:'DELETE'});loadAnnouncements()}}

async function loadGallery(){gallery=await api('/api/gallery');document.getElementById('galleryGrid').innerHTML=gallery.map(g=>`<div class="gallery-admin-card"><img src="${g.image}"><div><b>${esc(g.title||'School photo')}</b><button class="small-btn danger" onclick="deleteGallery(${g.id})">Delete</button></div></div>`).join('')||'<p>No gallery photos yet.</p>'}
function openGallery(){document.getElementById('galleryForm').reset();openModal('galleryModal')}
document.getElementById('galleryForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/gallery',{method:'POST',body:new FormData(e.target)});closeModal('galleryModal');loadGallery()}catch(err){alert(err.message)}});
async function deleteGallery(id){if(confirm('Delete this photo?')){await api('/api/gallery/'+id,{method:'DELETE'});loadGallery()}}

async function loadSite(){site=await api('/api/site');const keys=['school_name','tagline','eyebrow','about_title','about_text','about_text_2','vision','mission','objectives','facilities','future_goals','future_projects','admission_title','admission_text','admission_link','address','email','phone','chairman_name','chairman_role','slogan'];const labels={school_name:'School Name',tagline:'Tagline',eyebrow:'Hero Eyebrow',about_title:'About Heading',about_text:'About Paragraph 1',about_text_2:'About Paragraph 2',vision:'Vision',mission:'Mission (one point per line)',objectives:'Objectives (one point per line)',facilities:'Facilities (one point per line)',future_goals:'Future Goals (one point per line)',future_projects:'Future Projects',admission_title:'Admission Heading',admission_text:'Admission Details (one point per line)',admission_link:'Admission Link',address:'Address',email:'Email',phone:'Phone / WhatsApp',chairman_name:'Chairman Name',chairman_role:'Chairman Role',slogan:'Slogan'};document.getElementById('siteForm').innerHTML=keys.map(k=>`<label>${labels[k]}${['about_text','about_text_2','vision','mission','objectives','facilities','future_goals','admission_text'].includes(k)?`<textarea name="${k}" rows="4">${esc(site[k]||'')}</textarea>`:`<input name="${k}" value="${esc(site[k]||'')}">`}</label>`).join('');document.getElementById('sideLogo').src=site.logo||'/assets/Logo Al Azan/Logo Al Azan-1.png'}
async function saveWebsite(){const body=Object.fromEntries(new FormData(document.getElementById('siteForm')));try{await api('/api/site',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});alert('Website information saved successfully. Refresh the public website to see changes.');loadSite()}catch(e){alert(e.message)}}
async function uploadSiteImage(key,input){if(!input.files[0])return;const fd=new FormData();fd.append('key',key);fd.append('image',input.files[0]);try{await api('/api/site/image',{method:'POST',body:fd});alert('Image updated successfully.');loadSite()}catch(e){alert(e.message)}input.value=''}

async function sendSMS(selected){const message=document.getElementById('smsMessage').value.trim();if(!message)return alert('Write a message first.');let ids=null;if(selected){ids=[...document.querySelectorAll('.student-check:checked')].map(x=>Number(x.value));if(!ids.length)return alert('Select at least one student from Students.')}const className=document.getElementById('smsClass').value;try{const r=await api('/api/sms/bulk',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,studentIds:ids,className:ids?null:className})});document.getElementById('smsResult').textContent=`Sent ${r.sent} of ${r.total} messages.`}catch(e){document.getElementById('smsResult').textContent=e.message}}

document.querySelectorAll('.side[data-view]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.side[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));document.getElementById('view-'+b.dataset.view).classList.remove('hidden')}));
boot();
