const langBtn=document.getElementById('langBtn');let urdu=false;
langBtn?.addEventListener('click',()=>{urdu=!urdu;document.documentElement.dir=urdu?'rtl':'ltr';langBtn.textContent=urdu?'English':'اردو';document.body.classList.toggle('urdu',urdu)});
async function loadPublicContent(){try{const [site,staff,classes,announcements,gallery]=await Promise.all([fetch('/api/public/site').then(r=>r.json()),fetch('/api/public/staff').then(r=>r.json()),fetch('/api/public/classes').then(r=>r.json()),fetch('/api/public/announcements').then(r=>r.json()),fetch('/api/public/gallery').then(r=>r.json())]);
 const textMap={'#site-name':'school_name','#site-tagline':'tagline','#hero-eyebrow':'eyebrow','#about-title':'about_title','#about-text':'about_text','#about-text-2':'about_text_2','#vision-text':'vision','#slogan-text':'slogan','#admission-title':'admission_title','#admission-link':'admission_link','#contact-address':'address','#contact-email':'email','#contact-phone':'phone','#chairman-name':'chairman_name','#chairman-role':'chairman_role','#future-projects':'future_projects'};
 for(const [sel,key] of Object.entries(textMap)){const el=document.querySelector(sel);if(el&&site[key]){if(sel==='#admission-link'){el.href=site[key];el.textContent='Apply Online'}else el.textContent=site[key]}}
 document.querySelectorAll('[data-site-image]').forEach(img=>{const key=img.dataset.siteImage;if(site[key])img.src=site[key]});const logo=document.querySelector('.brand img');if(logo&&site.logo)logo.src=site.logo;
 const setList=(id,val)=>{const el=document.getElementById(id);if(!el||!val)return;el.innerHTML=val.split('\n').filter(Boolean).map(x=>`<li>${escapeHtml(x)}</li>`).join('')};setList('objectives-list',site.objectives);setList('mission-list',site.mission);setList('facilities-list',site.facilities);setList('future-list',site.future_goals);setList('admission-list',site.admission_text);
 const staffBox=document.getElementById('public-staff');if(staffBox){staffBox.innerHTML=staff.map(s=>`<article class="cards article"><img class="public-avatar" src="${s.photo||site.logo}" alt=""><h3>${escapeHtml(s.name)}</h3><b>${escapeHtml(s.role)}</b><p>${escapeHtml(s.bio)}</p></article>`).join('')||'<p>No staff profiles published yet.</p>'}
 const classBox=document.getElementById('public-classes');if(classBox){classBox.innerHTML=classes.map(c=>`<article class="cards article"><h3>${escapeHtml(c.name)} ${escapeHtml(c.section)}</h3><b>${escapeHtml(c.teacher)}</b><p>${escapeHtml(c.description)}</p></article>`).join('')||'<p>Class information will be published soon.</p>'}
 const news=document.getElementById('public-announcements');if(news){news.innerHTML=announcements.map(a=>`<article class="cards article"><span class="kicker">${escapeHtml(a.date)}</span><h3>${escapeHtml(a.title)}</h3><p>${escapeHtml(a.body)}</p></article>`).join('')||'<p>No new announcements.</p>'}
 const gal=document.getElementById('public-gallery');if(gal&&gallery.length){gal.innerHTML=gallery.map(g=>`<img src="${g.image}" alt="${escapeHtml(g.title||'School photo')}">`).join('')}
 document.title=site.school_name||document.title;
 }catch(e){console.warn('Public content load failed',e)} }
function escapeHtml(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
loadPublicContent();
